### ISSUE TITLE
Preflight checks should only perform when header "Access-Control-Request-Method" is present

### ISSUE THREAD

**Issue by rekrut** [nelmio/NelmioCorsBundle#100]
Otherwise request method "OPTIONS" exclusively get into a preflight check mode.

https://github.com/nelmio/NelmioCorsBundle/blob/4243c60a96f8b95d5f42a3e65b33a3eebc511491/EventListener/CorsListener.php#L72-L77

You better modify this to something like:

```
        // perform preflight checks
        if ('OPTIONS' === $request->getMethod() && $request->headers->get('Access-Control-Request-Method') != '') {
            $event->setResponse($this->getPreflightResponse($request, $options));

            return;
        }
```

**Comment by Kifah** [comment]
I am having the same issue with symphony 4.1

**Comment by scion4581** [comment]
@rekrut I am totaly agree, moreover next lines in getPreflightResponse method  will throw exception with 405 code, cause Access-Control-Request-Method is empty

https://github.com/nelmio/NelmioCorsBundle/blob/4243c60a96f8b95d5f42a3e65b33a3eebc511491/EventListener/CorsListener.php#L147-L152

**Comment by zegenie** [comment]
I'm also seeing this bug, where the preflight check kicks in for valid `OPTIONS` requests that are not preflight requests, as mentioned in a previous comment. Will this be fixed?
