### ISSUE TITLE
GNU license within test file

### ISSUE THREAD

**Issue by StephenOTT** [nelmio/NelmioCorsBundle#104]
https://github.com/nelmio/NelmioCorsBundle/blob/master/Tests/DependencyInjection/CorsConfigurationProviderPassTest.php#L6

Is this on purpose or a legacy thing?

**Comment by Seldaek** [comment]
I think this was a mistake by @bdunogier probably using default IDE settings to create the new test file. It probably should be removed as it indeed has no relation to the project's license.

**Comment by StephenOTT** [comment]
Thanks @Seldaek
