### ISSUE TITLE
Avoid preflight responses spamming New Relic

### ISSUE THREAD

**Issue by trompette** [nelmio/NelmioCorsBundle#108]
At https://laruchequiditoui.fr/, we have an API monitored with New Relic.

For some time we have a strange `/unknown` route with high throughput:

![image](https://user-images.githubusercontent.com/181746/45756525-5de48480-bc21-11e8-99fb-99d2e27a0ce3.png)

Looking at [the documentation](https://docs.newrelic.com/docs/agents/php-agent/troubleshooting/transactions-named-indexphp-or-unknown) we thought it was a configuration problem on our side.

But we calculated the route is about 30% of our traffic and when we looked at our HTTP logs, only responses of `OPTIONS` requests were generate in less than 10 ms.

These so-called preflight responses are [generated](https://github.com/nelmio/NelmioCorsBundle/blob/1.5.4/EventListener/CorsListener.php#L72-L77) by `NelmioCorsBundle`.

We are wondering if it would be a good idea to offer a configuration option to [ignore the transactions](https://docs.newrelic.com/docs/agents/php-agent/php-agent-api/newrelic_ignore_transaction).

Thoughts?

**Comment by Seldaek** [comment]
Why not I guess, but I'd say you could also do this in a request listener to ignore all OPTIONS requests if you are not interested in tracking these. That said if 30% of traffic is OPTIONS requests maybe you should check why that is.. Maybe it can be reduced?

**Comment by trompette** [comment]
> You could also do this in a request listener to ignore all OPTIONS requests.

That is exactly what we did, but we thought it would be nice to be part of `NelmioCorsBundle`.

An alternative to the configuration option could be a README addition. I can help by openning a PR.

> If 30% of traffic is OPTIONS requests maybe you should check why that is.

Our API is mostly authenticated routes, that is why.

Actually we were surprised that it was only 30%.

**Comment by Seldaek** [comment]
I'd rather a README PR because adding newrelic specific stuff in the code isn't so great IMO..
