### ISSUE TITLE
Response listener gets added multiple times in a ReactPHP environment

### ISSUE THREAD

**Issue by acasademont** [nelmio/NelmioCorsBundle#114]
Right now the listener assumes the EventDispatcher will be rebooted after every request as per the normal PHP way of handling requests, not the case in a ReactPHP app, where all services are long-lived and serve many requests. Therefore, on every CORS request, the response listener is added again to the EventDispatcher queue. Not sure if there's an easy way to prevent that without a considerable refactor.

**Comment by Seldaek** [comment]
This was fixed.. some time ago :D
