### ISSUE TITLE
NelmioCorsBundle / Error / Can t load a file

### ISSUE THREAD

**Issue by kamalkech** [nelmio/NelmioCorsBundle#118]
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "NelmioCorsBundle" from namespace "Nelmio\CorsBundle".
Did you forget a "use" statement for another namespace? in /app/src/Kernel.php:23
Stack trace:
#0 /app/vendor/symfony/http-kernel/Kernel.php(424): App\Kernel->registerBundles()
#1 /app/vendor/symfony/http-kernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /app/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
#3 /app/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/bin/console(38): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#5 {main}
  thrown in /app/src/Kernel.php on line 23

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "NelmioCorsBundle" from namespace "Nelmio\CorsBundle".
Did you forget a "use" statement for another namespace? in /app/src/Kernel.php on line 23

Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "NelmioCorsBundle" from namespace "Nelmio\CorsBundle".
Did you forget a "use" statement for another namespace? in /app/src/Kernel.php on line 23

Call Stack:
    0.0560    1942832   1. Symfony\Component\Debug\ErrorHandler->handleException() /app/vendor/symfony/debug/ErrorHandler.php:0

**Comment by thomasrm** [comment]
Did you solve this error in the end? I have the same issue.

Thanks
