### ISSUE TITLE
Tree builder without root node missed in 1.5.4

### ISSUE THREAD

**Issue by yuri-karkh** [nelmio/NelmioCorsBundle#120]
https://github.com/nelmio/NelmioCorsBundle/commit/001f2ece5cc435f4e35bbda2363f396072e27c68 is not in 1.5.4 even if it was committed.

**Comment by Seldaek** [comment]
@dunglas if you have a chance to make a release here that'd be great.. I'm really swamped atm sorry.

**Comment by dunglas** [comment]
I'll do it this afternoon!

**Comment by yuri-karkh** [comment]
thanks @dunglas
