### ISSUE TITLE
Malformed shell syntax for CORS_ALLOW_ORIGIN recipe defaults

### ISSUE THREAD

**Issue by fyrye** [nelmio/NelmioCorsBundle#149]
The default recipe installs with
`CORS_ALLOW_ORIGIN=^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$`

Which errors when loaded from shell.

```
source ./.env
```

Result
```
./.env: line 48: syntax error near unexpected token `('
./.env: line 48: `CORS_ALLOW_ORIGIN=^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
```
---

To resolve the issue, wrap the pattern in double quotes, which will be parsed out by symfony/dotenv and be properly configured in `shell`
```
CORS_ALLOW_ORIGIN="^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$"
```

**Comment by yannoff** [comment]
@fyrye \o/ Should be fixed by https://github.com/symfony/recipes/pull/849
