### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by dionx** [nelmio/NelmioCorsBundle#161]
PHP Fatal error:  Declaration of Fixtures\ProviderMock::getOptions(Symfony\Component\HttpFoundation\Request $request): void must be compatible with Nelmio\CorsBundle\Options\ProviderInterface::getOptions(Symfony\Component\HttpFoundation\Request $request): array in vendor/nelmio/cors-bundle/Tests/Fixtures/ProviderMock.php on line 14

**Comment by fd6130** [comment]
Do you have extra information about this error?

Like php version and Symfony version you are using now?

**Comment by dionx** [comment]
Yes, I have. php 7.4.12, symfony 4.4. I got this error while getting acquainted with the hautelook/alice-bundle. But it seems to me that these nuances are not particularly needed to understand the error. Take a closer look at declaration these methods:

1. https://github.com/nelmio/NelmioCorsBundle/blob/be4d5824caebc86da9e224e935e02e1201b3ea54/Tests/Fixtures/ProviderMock.php#L14
2. https://github.com/nelmio/NelmioCorsBundle/blob/be4d5824caebc86da9e224e935e02e1201b3ea54/Options/ProviderInterface.php#L39
