### ISSUE TITLE
Symfony 5: 502 Bad Gateway

### ISSUE THREAD

**Issue by SiMoSiMo2** [nelmio/NelmioCorsBundle#167]
I have some (fake) routes, like:
```
#[Route('/prova', name: 'prova', methods: ['GET'])]
public function prova(): Response
{
    return $this->json('SUCCESS', Response::HTTP_OK);
}
```
```
#[Route('/prova-post', name: 'prova-post', methods: ['POST'])]
public function prova(): Response
{
    return $this->json('SUCCESS', Response::HTTP_OK);
}
```
```
#[Route('/contacts/{id}', name: 'get-contact', methods: ['GET'])]
public function getContact(Contact $contact): Response
{
    return $this->json('SUCCESS', Response::HTTP_OK);
}
```
All these routes work correctly before installing this bundle.
After installing the bundle only `get-contact` endpoint works. The others return: 502 Bad Gateway

I've tried with the default `nelmio_cors.yaml` and also with the one provided by the readme file. Nothing has changed.

Any idea?

Symfony5.3, nginx 1.21, php8

**Comment by fd6130** [comment]
Hmmm is it because of the nginx config? Try with apache instead? Or you might need to do something about the config, i guess?
