### ISSUE TITLE
Symfony 6 compatibility

### ISSUE THREAD

**Issue by shude** [nelmio/NelmioCorsBundle#172]
Hi, symfony 6 just been released. Time to update compatibility with it.

**Comment by shude** [comment]
@Seldaek in master branch it's already changed composer.json, but tag 2.1.1 has no one.
```
"require": {
        "symfony/framework-bundle": "^4.3 || ^5.0"
    },
```

**Comment by javiercno** [comment]
Your can update tag, please? @Seldaek

**Comment by Seldaek** [comment]
https://github.com/nelmio/NelmioCorsBundle/releases/tag/2.2.0 is out
