### ISSUE TITLE
Is this project/repository abandoned?

### ISSUE THREAD

**Issue by nocive** [nelmio/NelmioCorsBundle#180]
I see several open PRs without any feedback from anyone in charge.
The same thing seems to happen with most reported issues, no feedback provided, dead silence.

So my question is, is this still maintained at all?

**Comment by Seldaek** [comment]
It is not abandoned per se no. I just don't have a lot of time for it, and it kinda just works. There are a few support issues but to be fair it's not my job to fix people's understanding of CORS nor their frontend implementations or their configuration. I use this on a few projects and never encountered any issues.

**Comment by nocive** [comment]
Thanks for the reply @Seldaek, appreciate it.
