### ISSUE TITLE
version 2.3.0 blocks use of psr/log:3.0.0, which the latest version of monolog/monolog requires

### ISSUE THREAD

**Issue by ovgray** [nelmio/NelmioCorsBundle#181]
version 2.3.0 composer.json adds a requirement of "psr/log": "^1.0".

This blocks use of "psr/log":"^3.0", which the latest version of monolog/monolog requires.

Is there some reason why the requirement is not "psr/log": "^1.0||^2.0||^3.0"?

**Comment by Seldaek** [comment]
No that is just an omission. Totally missed that in review, will fix tomorrow

**Comment by ovgray** [comment]
Thanks.
