### ISSUE TITLE
DependencyInjection\Extension deprecation warning

### ISSUE THREAD

**Issue by VarunAgw** [nelmio/NelmioCorsBundle#201]
The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "Nelmio\CorsBundle\DependencyInjection\NelmioCorsExtension".

**Comment by Seldaek** [comment]
Fixed by #200
