### ISSUE TITLE
405 When Access-Control-Request-Method Isn't Set

### ISSUE THREAD

**Issue by JProffitt71** [nelmio/NelmioCorsBundle#21]
Not sure if bug or feature:

When using this in combination with the NelmioApiDocBundle I noticed that the sandbox didn't work when making request with a json body. I figured out that the sandbox was performing a OPTIONS request without an "Access-Control-Request-Method" header, and tracked the issue down to `line 135` in `@NelmioCorsBundle/EventListner/CorsListener.php`:

```
if (!in_array($request->headers->get('Access-Control-Request-Method'), $options['allow_methods'], true)) {
```

It works with this tweak:

```
if (!is_null($request->headers->get('Access-Control-Request-Method')) && !in_array($request->headers->get('Access-Control-Request-Method'), $options['allow_methods'], true)) {
```

**Comment by Seldaek** [comment]
@LPodolski can you send a PR?

**Comment by oskarcalvo** [comment]
Hello, I also have the bug.

Any idea when will be fix it?

**Comment by zegenie** [comment]
This bug isn't fixed so it shouldn't be closed. As mentioned in https://github.com/nelmio/NelmioCorsBundle/issues/21#issuecomment-418023782, the bundle interferes with valid CORS  `OPTIONS` requests, which aren't preflight requests.

**Comment by Julen10** [comment]
This bug isn´t present on nelmio/cors-bundle version **1.5.6**

**Comment by gustawdaniel** [comment]
This is critical bug. This issue should be reopened and.

**Comment by xoxmaman** [comment]
When the request has the same values in headers Origin and Host than method CorsListener::onKernelRequest returns in line 69 and request goes into a controller where OPTIONS method is disallowed.

`// skip if not a CORS request
        if (!$request->headers->has('Origin') || $request->headers->get('Origin') == $request->getSchemeAndHttpHost()) {
            return;
        }`

TBH I don't understand why the request is not CORS when a value of Origin header is the same as $request->getSchemeAndHttpHost()
