### ISSUE TITLE
Allow URL parameters

### ISSUE THREAD

**Issue by nicolasmure** [nelmio/NelmioCorsBundle#41]
Hi,

Thanks for your bundle :+1: 
I'm having troubles when accessing to an address with URL parameters : 
```
GET http://my.symfony.root.url/efconnect?cmd=open&target=&init=1&tree=1&_=1423215615264

Status 200 OK, Cross-Origin Request blocked.
```
I've though allowed the `^/efconnect` path in my nemlio cors config.
You can have more details about my problems here : https://github.com/helios-ag/FMElfinderBundle/issues/106

It seems like URL parameters are not well handled :open_mouth: .
I'm not sure this problem may concern your bundle or not. If not, sorry for disturbance :stuck_out_tongue: .
Thanks for help :wink:

**Comment by Seldaek** [comment]
The config and all look good so I am not sure why it fails, could you maybe check in the web browser console if it gives more details? Also if you can post a screenshot of the complete request and response headers that'd be interesting.

**Comment by nicolasmure** [comment]
Thanks for your answer, here are some screenshots on both Firefox and Chrome browsers : 

![capture](https://cloud.githubusercontent.com/assets/4362252/6102696/60bdce8c-b03b-11e4-881f-162a388c2858.png)

![capture-1](https://cloud.githubusercontent.com/assets/4362252/6102700/6b3054ca-b03b-11e4-85e3-d98e28ef4bbe.png)
![capture-2](https://cloud.githubusercontent.com/assets/4362252/6102701/6e6a352a-b03b-11e4-8ccc-ef9cf563ae6b.png)

Hope it helps.

To skirt the problem, I can use an iframe : 
```html
<iframe src="http://dev.webtool2.fr/app_dev.php/elfinder" width="800px" height="600px"></iframe>
```

The request is not blocked and I get my json return : 

![capture-3](https://cloud.githubusercontent.com/assets/4362252/6102827/cdae231a-b03c-11e4-8717-4bcb8b64d720.png)


```
XHR finished loading: GET "http://dev.webtool2.fr/app_dev.php/efconnect?mode=&cmd=open&target=l1_Lw&init=1&tree=1&_=1423469712999".
```
![capture-5](https://cloud.githubusercontent.com/assets/4362252/6102823/cb4a77b8-b03c-11e4-97f3-24505618b587.png)

But I would prefer to use the "normal" way to initialize the plugin to make it easier to handle with angularJS, instead of using an iframe.

May it be XHR requests causing this problem?

**Comment by nicolasmure** [comment]
Ok, after a deeper look the problem might be because of a hard `exit`, that's why `onKernelResponse` function of the `CorsListener` class is never called.

This is how it goes : 

1. Request `http://my.symfony.root.url/efconnect?cmd=open&target=&init=1&tree=1&_=1423215615264` ends on [`ElFinderController::loadAction`](https://github.com/helios-ag/FMElfinderBundle/blob/master/Controller/ElFinderController.php#L120) function. This function creates a loader and runs it.
2. The loader creates a connector and runs it : [`ElFinderLoader::load`](https://github.com/helios-ag/FMElfinderBundle/blob/master/Loader/ElFinderLoader.php#L54)
3. The connector is building the final answer : [`ElFinderConnector::run`](https://github.com/helios-ag/ElFinderPHP/blob/master/src/Connector/ElFinderConnector.php#L57)
4. The connector finally calls [`ElFinderConnector::output`](https://github.com/helios-ag/ElFinderPHP/blob/master/src/Connector/ElFinderConnector.php#L119) function who writes data on output with **`json_encode`**  and **`exit`**.

The normal SF cycle can't go on and response never goes in CORS activation function.

I don't think your bundle is involved in this problem.
Should I close this issue?
Does anyone agree with me or am I mistaking?

**Comment by Seldaek** [comment]
Yes indeed a hard exit would do the trick to mess up with the bundle's operation. Not much we can do there.

**Comment by nicolasmure** [comment]
Yes, sorry for disruption...
and thanks for help and consideration :+1:  :wink: 


See you.
