### ISSUE TITLE
Use annotation on CORS-enabled routes

### ISSUE THREAD

**Issue by stivni** [nelmio/NelmioCorsBundle#43]
I think it would be nice to be able to add an annotation to a route for which you want to enable CORS.

``` php

/**
* @Route("/your/cors/enable/route")
* @Method("POST")
* @Cors()
*/
public function login()
{
    return new Response("...");
}
```

You could optionally provide a key of a configuration, if you don't want to use the default values. e.g. `@Cors("api")`

In this way, you are far more flexibel in configuration (you loose al the pattern matching stuff) and it makes cors enabling more verbose.

Any thoughts?

**Comment by kcivey** [comment]
+1

**Comment by Quberik** [comment]
+1

**Comment by hason** [comment]
:+1:

**Comment by liyo** [comment]
Yes

**Comment by Seldaek** [comment]
Sounds good yes I agree, but I am not sure if or when I'll have time to work on it so if any of you feels like sending a PR please do :)

**Comment by bigfoot90** [comment]
+1

**Comment by Seldaek** [comment]
Closing as it seems nobody had any interest in pushing this further.
