### ISSUE TITLE
Is there a way to enable CORS for an image?

### ISSUE THREAD

**Issue by nicolasmure** [nelmio/NelmioCorsBundle#46]
Hi,

Tanks for your bundle!
I was wondering if there is a way to enable CORS for an image (ie accessed directly from its own URL and not from a route).
I'm trying to modify this image from the front end using some javascript : 
``` javascript
var canvas = document.createElement('canvas');
var ctx = canvas.getContext('2d');
var imgObj = new Image();
imgObj.crossOrigin = 'anonymous';
imgObj.src = src; // http://dev.myapp.com/files/image.jpg
canvas.width = imgObj.width;
canvas.height = imgObj.height;
ctx.drawImage(imgObj, 0, 0);
var imgPixels = ctx.getImageData(0, 0, canvas.width, canvas.height); // <== ERROR
````
getImageData function throws an error :

Image from origin 'http://dev.myapp.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.

I've tried to add the following config to my config.yml file but it does not work :
```yml
'^/files/':
    allow_origin: ['*']
    allow_headers: ['*']
    allow_methods: ['GET']
    max_age: 3600
    allow_credentials: true
```

Do you know how to solve this problem? Accessing the image directly does not seems to run the symfony process and so it does not run the hooks of the bundle...
Any comments are appreciated,

thanks :smile:

**Comment by stof** [comment]
Images are generally served by your webserver directly, not by your Symfony application (unless doing something crazy), which means you have to add CORS headers in the webserver config directly, not in the Symfony project

**Comment by nicolasmure** [comment]
OK thanks for your answer :+1:
