### ISSUE TITLE
Access-Control-Allow-Origin should not be set when regex does not match

### ISSUE THREAD

**Issue by teohhanhui** [nelmio/NelmioCorsBundle#50]
`Access-Control-Allow-Origin: null` is treated as an invalid value by the browser.

**Comment by Seldaek** [comment]
The point is that it does not allow the request though so it's not a problem is it?

**Comment by toverux** [comment]
Yes but it displays - I suppose - an error about an invalid value in the header, that could let the developer think there's a problem in the bundle. In contrast, a missing header should lead to display a non-ambiguous message saying that the request is not allowed.

**Comment by teohhanhui** [comment]
@toverux Exactly! :)

**Comment by teohhanhui** [comment]
`Access-Control-Allow-Origin: null` actually has a special meaning. It's used for e.g. local files.

**Comment by Seldaek** [comment]
OK I see, would you mind sending a pull request fixing this then?
