### ISSUE TITLE
can't install NelmioCorsBundle with composer

### ISSUE THREAD

**Issue by TaktakTaktouk** [nelmio/NelmioCorsBundle#56]
HI!
when i try to run `composer require nelmio/cors-bundle` in composer with symfony 2.8 i have this error:
![sans titre](https://cloud.githubusercontent.com/assets/6607740/12670571/cfbcb27c-c669-11e5-8f88-b2c96836fb85.jpg)

**Comment by TaktakTaktouk** [comment]
It's beceause my composer is not up to date.
Sorry

**Comment by OskarStark** [comment]
this issue can  be closes
