### ISSUE TITLE
Preflight error 401 with Symfony 3.1.3

### ISSUE THREAD

**Issue by nico-incubiq** [nelmio/NelmioCorsBundle#64]
Hi,

CORS preflight calls are being rejected with a 401 error code on my API since I tried upgrading to Symfony 3.1.3.
I am using NelmioCorsBundle 1.4.1.
My API is protected by a firewall which requires authentication, so I guess the CORS listener is being called too late...

Symfony 3.1.2 works just fine, so a commit in-between must have broken the CORS preflight calls. I'd say either [[Security] fixed DebugAccessDecisionManager::setVoters()](https://github.com/symfony/symfony/pull/19272/files) or [[HttpFoundation] Add OPTIONS and TRACE to the list of safe methods](https://github.com/symfony/symfony/pull/19321/files)

Here is a log of my issue if that can help you:
`security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at /website/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:53)"}`

Thanks, regards,

Nicolas

**Comment by stephadz** [comment]
Same problem after upgrade of Symfony 2.8.8 to 2.8.9. 
NelmioCorsBundle 1.4.1.
Tested with PHP 5.6.19 / PHP 5.6.20 / PHP 5.6.22

I have collected some useful logs : 

With SF 2.8.8 (works well)
```
event.DEBUG: Notified event "kernel.request" to listener "Nelmio\CorsBundle\EventListener\CorsListener::onKernelRequest". [] []
event.DEBUG: Listener "Nelmio\CorsBundle\EventListener\CorsListener::onKernelRequest" stopped propagation of the event "kernel.request". [] []
event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure" was not called for event "kernel.request". [] []
```

After upgrading SF 2.8.9 
```
event.DEBUG: Notified event "kernel.request" to listener "Nelmio\CorsBundle\EventListener\CorsListener::onKernelRequest". [] []
event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". [] []
```

We can see the event "kernel.request" is not stopped by NelmioCors...
is it NelmioCors or Sf bugs?

**Comment by valotvince** [comment]
Hi there,
I wrote this issue, it seems to be the same error :) 
https://github.com/symfony/symfony/issues/19582

**Comment by nico-incubiq** [comment]
Guys at Symfony published a fix for this issue. I think it is safe to close now.
