### ISSUE TITLE
Allow all subdomains of current domain only

### ISSUE THREAD

**Issue by mort3za** [nelmio/NelmioCorsBundle#65]
When I use ['*'] everything works great but I want to allow only main domain and all of (wildcard) subdomains to access api. Something like this:

```allow_origin: ['CURRENT_DOMAIN', '*.CURRENT_DOMAIN']```

Any ideas?

**Comment by Seldaek** [comment]
We don't support wildcards but we support an origin_regex option. If you
set it to true then you can use something like allow_origin: ['^http://
(.+\.)?example\.com']
