### ISSUE TITLE
Be able to force Access-Control-Allow-Origin header value

### ISSUE THREAD

**Issue by Oliboy50** [nelmio/NelmioCorsBundle#66]
## Current state

"Access-Control-Allow-Origin" header is set using the request's "Origin" header value ([pre-flight request](https://github.com/nelmio/NelmioCorsBundle/blob/master/EventListener/CorsListener.php#L129) or [not](https://github.com/nelmio/NelmioCorsBundle/blob/master/EventListener/CorsListener.php#L94))
## Issue

Let's say I have 2 differents hosts ("front1.example.com" and "front2.sample.com") which do AJAX calls to my API ("api.json.com").
But I also have a cache system (e.g. Varnish) which resend responses to already sent requests.
So when `front1.example.com` calls `api.json.com`, the "Access-Control-Allow-Origin" header of the response is `front1.example.com`.
But when `front2.sample.com` calls `api.json.com` with the same URL, my cache system reuse the previous response, so the "Access-Control-Allow-Origin" header of the response is still `front1.example.com`... and the browser say "You're not allowed... Cross origin blabla...".
## Possible fix

Add a configuration option to let the user set the value of the header "Access-Control-Allow-Origin" to be `*` for instance... or anything else.

**Comment by Seldaek** [comment]
I think we could have an option to say "send all allowed origins" instead of only sending the currently requested origin back. I don't remember if `*` is a valid response value for the allowed origin, but if it is that could also be sent back as is. Would you like to work on a pull request adding that feature?

**Comment by Oliboy50** [comment]
@Seldaek yup, `*` is perfectly valid (i'll double check that but it works :D)
Yep, you'll see a PR soon 👍

**Comment by Oliboy50** [comment]
However I think we really should let the user write anything he want in this header, because as the [documentation states](https://www.w3.org/TR/cors/#access-control-allow-origin-response-header), we can put `*` or a single origin or a space separated list of origins 

So It could be safer to do `Access-Control-Allow-Origin: https://front1.example.com https://front2.sample.com` instead of `Access-Control-Allow-Origin: *`... It should be up to users to choose what fit best for them, don't you think so?

**Comment by Seldaek** [comment]
Yeah maybe we should just always return what is configured as long as the
origin_Regex option isn't enabled.. I think the only reason it isn't done
is to keep the response shorter but if it causes cache issues it's maybe
not worth it.

**Comment by Oliboy50** [comment]
@Seldaek I added an option to force the header value :  https://github.com/nelmio/NelmioCorsBundle/pull/67

it's maybe too much and confusing, we could just always return `allow_origin` value as you said, but I still don't know what we should do when `origin_regex = true`, so I did something as simple as possible

**Comment by Oliboy50** [comment]
@Seldaek Thanks for merging this PR, but it seems we still have a Cache issue even with this...

The problem now, is that this bundle **only** add the `Access-Control-Allow-Origin: *` in the response **if** the request contains a `Origin` header... 

it means that if we cache a response (using Varnish for instance) that didn't contain the `Access-Control-Allow-Origin: *` header, when someone will send the same request but with the `Origin` header, the cached response will be returned and we'll have a CORS issue 😢 

So, I want to make another PR to `force the listener to set the Access-Control-Allow-Origin header`, but I wonder what is the best way of doing it. 

Here is 2 options, I'll code the one you chose:

1. Add an option `always_set_allow_origin_header` (could be `true` or `false`) which will always set the `Access-Control-Allow-Origin` header in the response when possible (if we know the value that the header should have). 
  => No breaking change but overkill IMHO, because it'll most likely only be used along with the `forced_allow_origin_value` option to solve cache issue like mine.
2. Update the code of `forced_allow_origin_value` option to always return the header.

**Comment by Seldaek** [comment]
I think the best really would be to set a `Vary: Origin` header in the 
response that way caches should do the right thing..

**Comment by Oliboy50** [comment]
@Seldaek you're right, but the main purpose for which I (and other folks I know) use this bundle: is to get rid of the CORS issues as quickly/easily as possible => if I could, I'd directly tells Chrome/Firefox to not bother me with CORS at all :)

**Comment by Seldaek** [comment]
I don't see how making the bundle send a vary header would prevent it from
getting cors done quick and easy?!

**Comment by Oliboy50** [comment]
@Seldaek oh, I see, I thought you were talking about my specific project, I didn't understand you wanted to do it in the bundle itself

I think it's a good idea yes 👍 

So should I remove the `forced_allow_origin_value` option and just **always** add the Vary header in my PR?

**Comment by Oliboy50** [comment]
@Seldaek now I think there's only 1 problem about the "add vary in the bundle" solution... it makes the bundle touching stuff that may be used for completely something else than CORS stuff

=> Most people (at least I) will set their Vary headers using [`HttpFoundation\Response::setVary() method`](http://api.symfony.com/3.2/Symfony/Component/HttpFoundation/Response.html#method_setVary) or [`HttpFoundation\ResponseHeaderBag::set() method`](http://api.symfony.com/3.2/Symfony/Component/HttpFoundation/ResponseHeaderBag.html#method_set) without even know about the `bool $replace = true` default parameter... 

So we won't be able to set the Vary header in the bundle seemlessly without the risk of letting the user override it in its project
