### ISSUE TITLE
Add Symfony related GitHub topics

### ISSUE THREAD

**Issue by ste93cry** [nelmio/NelmioCorsBundle#74]
Now that Github introduced the topics feature for all repositories, Symfony proposed in [this](http://symfony.com/blog/standardizing-the-github-topics-for-symfony-repositories) blog post to standardize some tags for all Symfony related repositories to make easier to discover them. The official  recommendation is to add **php**, **symfony**, **bundle** and **symfony-bundle** topics and then, your own specific topics.

**Comment by Seldaek** [comment]
Done
