### ISSUE TITLE
Composer post-update-cmd error

### ISSUE THREAD

**Issue by andreaskas** [nelmio/NelmioCorsBundle#77]
After upgrading to the latest version 1.5.2, the following error appears and the composer fails during post-install-cmd

>   [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                       
  The service "nelmio_cors.options_provider.config" has a dependency on a non-existent parameter "nelmio_cors.map".  
                                                                                                                     

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

                                                                                                                         
  [RuntimeException]                                                                                                     
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                              
                                                                                                                         
    [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                         
    The service "nelmio_cors.options_provider.config" has a dependency on a non-existent parameter "nelmio_cors.map".    
                                                                                                                         
  
Downgrading to 1.5.1 seems to fix the issue. Any thoughts?

**Comment by Seldaek** [comment]
Can you share your nelmio_cors config block?

**Comment by Seldaek** [comment]
Also ping @leofeyer ;)

**Comment by jaydlawrence** [comment]
Same issue here. Downgraded to 1.5.1 to get around it for now.

**Comment by leofeyer** [comment]
@andreaskas @jaydlawrence How did you configure the bundle in your `config.yml` file?

**Comment by leofeyer** [comment]
😠  Fixed in #78.

**Comment by Seldaek** [comment]
1.5.3 is out
