### ISSUE TITLE
Symfony Flex Recipe

### ISSUE THREAD

**Issue by juliusstoerrle** [nelmio/NelmioCorsBundle#84]
Hey, will there be a recipe for symfony flex on https://github.com/symfony/recipes-contrib?

Here is the Guide on how to create one: https://github.com/symfony/recipes

I haven't created any recipe yet, but i can try if you like me to do so.

**Comment by nicraMarcin** [comment]
+1

**Comment by vlad-tuznichenko** [comment]
+1

**Comment by acidline** [comment]
+1
