### ISSUE TITLE
Attempted to load class "NelmioCorsBundle"

### ISSUE THREAD

**Issue by ObadaAbdelkareem** [nelmio/NelmioCorsBundle#93]
I have included the  NelmioCorsBundle on the AppKernel.php  like below : 
```
    public function registerBundles(): array
    {
        $bundles = [
            new \Sylius\Bundle\AdminBundle\SyliusAdminBundle(),
            new \Sylius\Bundle\ShopBundle\SyliusShopBundle(),

            new \FOS\OAuthServerBundle\FOSOAuthServerBundle(), // Required by SyliusAdminApiBundle.
            new \Sylius\Bundle\AdminApiBundle\SyliusAdminApiBundle(),
            new Nelmio\CorsBundle\NelmioCorsBundle(),
            new \AppBundle\AppBundle(),
        ];
```

but still give me this error 

Attempted to load class "NelmioCorsBundle" from namespace "Nelmio\CorsBundle".Did you forget a "use" statement for another namespace?
--
 can

**Comment by stefandoorn** [comment]
Have you required it via Composer also? 

`composer require nelmio/cors-bundle`

**Comment by carnau** [comment]
Maybe he forgot to execute `composer install`.

**Comment by ricardosaracino** [comment]
Name space does not start with a slash

**Comment by thomasrm** [comment]
Any progress regarding this issue? I'm having the exact same one.

I installed CorsBundle with `composer require nelmio/cors-bundle`

Thanks!

**Comment by ayyoub-afwallah** [comment]
`composer require nelmio/cors-bundle` works !

**Comment by USSIZ** [comment]
We have the same problem here.

Even with `composer require nelmio/cors-bundle` and trying to configure `nelmio_cors.yaml`

Any tip to resolve this ?
