### ISSUE TITLE
OPTIONS - return 405 Method not allowed

### ISSUE THREAD

**Issue by kingramizy** [nelmio/NelmioCorsBundle#96]
I configure nelmio for my api, (I use fosrestbundle and symfony 3.4)

my config.yml : 

![capture4](https://user-images.githubusercontent.com/9628047/38143358-742d7f44-3440-11e8-8a0e-21b07f7e4794.PNG)

one of my actions : 

        /**
         * @Rest\View()
         * @Rest\Get("api/v1/langue")
         */
        public function getLanguesAction(Request $request){
        $em = $this->getDoctrine()->getManager();

        $langues = $em->getRepository('PDFWSVisionLangueBundle:Langue')->findBy(array('laArchive' => '0'));
        //var_dump($langue);
        if (empty($langues)) {
            return new JsonResponse(['message' => 'not found'], Response::HTTP_NOT_FOUND);
        }
        
        $formatted = [];
        
        foreach ($langues as $langue) {
            $formatted[] = [
                'La_id' => $langue->getLaId(),
                'La_code' => $langue->getLaCode(),
                'La_libelle' => $langue->getLaLibelle(),
                'La_ordre' => $langue->getLaOrdre(),
                //'La_image' => $langue->getLaImage(),
             ];
        }
        return $formatted;
    }

when I call this function: / api / v1 / language in GET
I have : 
`
        {
    "error": {
        "code": 405,
        "message": "Method Not Allowed",
        "exception": [
            {
                "message": "No route found for \"OPTIONS /api/v1/langue\": Method Not Allowed (Allow: GET)",
                "class": "Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException",
`

what is wrong in my configuration?

**Comment by rickerd** [comment]
I've got the same problem...
Apache has the correct headers shown in the response below.

My setup is:
- Symfony3
- FosrestBundle
- NelmioCorsBundle
- ReactJS with axios as ajax library

![schermafbeelding 2018-03-31 om 21 19 03](https://user-images.githubusercontent.com/1032429/38167296-51386e9c-3533-11e8-9135-8e3b4f6ac6c9.png)

![schermafbeelding 2018-03-31 om 22 32 10](https://user-images.githubusercontent.com/1032429/38167301-63b3eeca-3533-11e8-9ec5-5f7638918c5f.png)

**Comment by rickerd** [comment]
No update?

**Comment by nataliaAznar** [comment]
I have the same problem.
My config is:
```yaml
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        max_age: 3600
    paths:
        '^/': ~
```

**Comment by rickerd** [comment]
What errors do you get? Because in the end it was not Nelmio but Apache what caused my problem.

**Comment by nataliaAznar** [comment]
I just get a 405 without any message
But I am using Nginx

**Comment by leonardorifeli** [comment]
I have the same problem. Any idea?
